### ISSUE TITLE
Not working with oxygen 22.1

### ISSUE THREAD

**Issue by ghedlund** [oxygenxml/dita-latex#1]
I have followed the instructions at https://www.oxygenxml.com/doc/versions/22.1/ug-editor/topics/dita-embedding-latex-equations.html. I've copied the com.oxygenxml.latex.svg folder to my /Applications/Oxygen XML Editor/frameworks/dita/DITA-OT3.x/plugins/ folder as in previous versions of the application. Equations appear in Author visual mode but do not appear in final pdf/html outputs. No error/warning appears in the log.

**Comment by raducoravu** [comment]
Did you run the DITA OT integrator?
https://www.oxygenxml.com/doc/versions/22.1/ug-editor/topics/dita-ot-install-plugin.html
Did this work for you with previous Oxygen versions? To what output formats are you publishing?

**Comment by ghedlund** [comment]
Thanks - I forgot this step :P My bad!

**Comment by raducoravu** [comment]
No problem, at least I found out somebody is using my plugin 👍
