### ISSUE TITLE
Working with standalone DITA-OT?

### ISSUE THREAD

**Issue by smartmic** [oxygenxml/dita-latex#2]
I am new to DITA and want to test some functionalities (among those LaTeX equations) before switching for "real" documentation projects.  I have the same problems like in the [other issue and saw your comment ](https://github.com/oxygenxml/dita-latex/issues/1#issuecomment-664348593 ).  But I do not have Oxygen installed. Is it a requirement or can I run this plugin also only with DITA-OT (`dita`) on the command line ? I tried this but the output, both HTML and PDF, remains empty when using the _testEquation.dita_ file as input.

**Comment by raducoravu** [comment]
The plugin, once copied to the DITA OT "plugins" folder and installed/integrated should just work, even from the command line. Did you test the publishing against the samples I prepared in the project?

 https://github.com/oxygenxml/dita-latex/tree/master/com.oxygenxml.latex.svg/samples

Is there any error reported in the DITA OT console output if you use the "-v -d" command line arguments when starting the "dita" command line?

**Comment by smartmic** [comment]
There is a problem already at installation, I got this error after running `dita install`:
`Error: Plug-in com.oxygenxml.latex.svg uses an undefined extension point com.oxygenxml.pdf.css.xsl.merged2html5`

**Comment by raducoravu** [comment]
Alright, that's easy to fix, remove from the plugin.xml this line:

    <feature extension="com.oxygenxml.pdf.css.xsl.merged2html5" value="xsl/xhtmlSVG.xsl" type="file"/>

unfortunately I cannot specify in the plugin.xml that an extension point is optional and that the integrator should not fail if a certain plugin is not installed.

**Comment by smartmic** [comment]
Yep, that was the culprit, fixed it. Thank you very much for the help and the work on this very nice plugin! The result looks beautiful both in PDF and HTML.

**Comment by raducoravu** [comment]
Thanks for the kind words 👍
