### ISSUE TITLE
Error with libfreetype

### ISSUE THREAD

**Issue by gbebie-valerian-antidot** [oxygenxml/dita-latex#3]
Hello Radu!
When I generate an output, I got an error in the build with libfreetype:
_[31mError: The following error occurred while executing this line:
java.lang.UnsatisfiedLinkError: libfreetype.so.6: cannot open shared object file: No such file or directory[0m_

What is the purpose of libfreetype? If I understand it handles truetype fonts, but I wonder if there's any way to get rid of this error by using another library or font management?

Thanks for your support!

**Comment by raducoravu** [comment]
@gbebie-valerian-antidot can you possibly save to a text file and attach the entire console log? I need to see more context... On what operating system are you publishing?

**Comment by gbebie-valerian-antidot** [comment]
Hi @raducoravu 
Sorry for the delay, I was waitig feedback from my colleagues who are in charge of the libraries in the connector. It seems we missed specific packages to be installed. Now it works well :)

**Comment by gbebie-valerian-antidot** [comment]
Not an issue related to the plugin. I had to install other libraries according to this link:
https://github.com/GoogleContainerTools/distroless/pull/322
